before_build:
    - nuget restore

build_script:
    - cmd: >-
        msbuild Migraw.sln /property:Configuration=Release

assembly_info:
    patch: true
    file: src\Properties\AssemblyInfo.cs
    assembly_version: $(APPVEYOR_BUILD_VERSION)
    assembly_file_version:
    assembly_informational_version: '$(APPVEYOR_BUILD_VERSION)-$(APPVEYOR_REPO_COMMIT)'

artifacts:
    - path: src\bin\Release

deploy:
    description: 'Migraw'
    provider: GitHub
    auth_token:
        secure: my3FMGAuyIX8zJLUhEdeY5Rcf72RiOd2r6tk/poTqEBe77TQzAUeVv+dKNGbVudM
    artifact: src\bin\Release.zip
    draft: true
    prerelease: false
    on:
        appveyor_repo_tag: true