before_build:
    - nuget restore

build_script:
    - cmd: >-
        msbuild Migraw.sln /property:Configuration=Release

assembly_info:
  patch: true
  file: src/Properties/AssemblyInfo.cs
  assembly_version: $(appveyor_build_version)
  assembly_file_version: $(appveyor_build_version)

artifacts:
    - path: src/bin/Release